name: dev_test_project
on:
  push:
    branches: [main]
    paths: ["**.py", "**.c", "**.h", "**.toml", "*languages.json", "*MANIFEST.in"]
  pull_request:
    branches: [main]
    paths: ["**.py", "**.c", "**.h", "**.toml", "*languages.json", "*MANIFEST.in"]
    types: ["opened", "reopened", "synchronize"]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]
    
    container:
      image: python:${{ matrix.python-version }}
    
    steps:
      - uses: actions/checkout@v5

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build Python
        run: | 
          python3 -m pip install --upgrade pip
          pip install build pytest
          pip install -e . --force-reinstall
      
      - run: pytest -s
